<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<input type="checkbox" <?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?>  name="newsletter:subscribe"> <label for="newsletter:subscribe" style="width: 90%; float: none;"><?php /* @escapeNotVerified */ echo __('Subscribe to Newsletter'); ?></label><br/>
